### ISSUE TITLE
BackupRequest doesn't work with streaming

### ISSUE THREAD

**Issue by zizhong** [linkedin/rest.li#573]
Currently, the BackUpRequest feature doesn't work well with stream requests. An exception raised due to SetReader() is invoked twice for the same EntityStream.

```com.linkedin.venice.client.exceptions.VeniceClientException: java.lang.IllegalStateException: EntityStream had already been initialized and can no longer accept Observers or Reader
at com.linkedin.venice.client.store.transport.D2TransportClient$1.onError(D2TransportClient.java:191) ~[venice-thin-client-0.2.68.jar:?]
at com.linkedin.d2.balancer.clients.BackupRequestsClient$DecoratedCallback$1.onError(BackupRequestsClient.java:471) ~[d2-27.3.17.jar:?]
at com.linkedin.r2.transport.common.bridge.client.TransportCallbackAdapter.onResponse(TransportCallbackAdapter.java:47) ~[r2-core-27.3.17.jar:?]
```

**Comment by ChrisCarini** [comment]
The [linkedin/rest.li](https://github.com/linkedin/rest.li) repository is being archived - see https://github.com/linkedin/rest.li/issues/1178 for details.

Ahead of it's archiving, we are closing all issues and PRs.
