### ISSUE TITLE
quickstart guide gradle build doesn't work

### ISSUE THREAD

**Issue by vshwnth2** [linkedin/rest.li#86]
Trying to follow https://github.com/linkedin/rest.li/wiki/Quickstart:-A-Tutorial-Introduction-to-Rest.li

On the first gradle build command inside /api folder, i get the following error: 

> Task :api:generateDataTemplate FAILED
[main] INFO com.linkedin.pegasus.generator.PegasusDataTemplateGenerator - Generating 1 files
Exception in thread "main" java.io.IOException: /Users/maheshvishwanath/sante-restli/api/src/mainGeneratedDataTemplate/java: non-existent directory
        at com.sun.codemodel.writer.FileCodeWriter.<init>(FileCodeWriter.java:73)
        at com.linkedin.pegasus.generator.PegasusDataTemplateGenerator.run(PegasusDataTemplateGenerator.java:152)
        at com.linkedin.pegasus.generator.PegasusDataTemplateGenerator.main(PegasusDataTemplateGenerator.java:105)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':api:generateDataTemplate'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

**Comment by vshwnth2** [comment]
stacktrace:

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':api:generateDataTemplate'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:382)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:31)
        at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:74)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:784)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:751)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more

**Comment by DongQuYiPiLang** [comment]
should be the gradle version issue, if you use gradle 4.0, it will be fine, good luck!

**Comment by vishalcjha** [comment]
@DongQuYiPiLang i did gradle wrapper on root level and then used ../gradlew build to build api. It worked for me. I guess 4.1 also works.

**Comment by evanw555** [comment]
@vshwnth2 This is quite a delayed follow-up, but this was resolved, yeah?

**Comment by venkyvb** [comment]
The quick-start seems to be broken again. When I go the `/api` folder and do a `gradle build` I see the following error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/rest.li-master/examples/quickstart/build.gradle' line: 12

* What went wrong:
A problem occurred evaluating root project 'quickstart'.
> Cannot add task 'wrapper' as a task with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 436ms
```

When I change the following in the `/rest.li-master/examples/quickstart/build.gradle` 

```
task wrapper(type: Wrapper) {
  gradleVersion = '4.6'
}
```

to

```
wrapper {
  gradleVersion = '4.6'
}
```

and then try `gradle build` in the `/api` folder I see the following error:

```
> Task :api:changedFilesReport FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':api:changedFilesReport'.
> You must declare outputs or use `TaskOutputs.upToDateWhen()` when using the incremental task API

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 637ms
6 actionable tasks: 1 executed, 5 up-to-date
```

any ideas as to what could be going wrong?

**Comment by evanw555** [comment]
@venkyvb Yeah, my guess is that this is something we forgot to clean up when upgrading to Gradle 5. See how we removed the `wrapper` task for the root build script in linkedin#241. I'm inferring that the guy who did the work didn't try building these sample projects (people often forget they're there). Could you try removing the wrapper task definition altogether? If it works, feel free to open a PR to fix this.

**Comment by liz2020** [comment]
@evanw555 I tried removing the wrapper task (line 12 - 14 in build.gradle) and it builds successfully. So, your suggestion works!

**Comment by viju4u** [comment]
Task :api:generateDataTemplate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':api:generateDataTemplate' (type 'GenerateDataTemplateTask').
  - In plugin 'pegasus' type 'com.linkedin.pegasus.gradle.tasks.GenerateDataTemplateTask' method 'generateFieldMask()' should not be annotated with: @Input.

    Reason: Input/Output annotations are ignored if they are placed on something else than a getter.

    Possible solutions:
      1. Remove the annotations.
      2. Rename the method.

    Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#ignored_annotations_on_method for more details about this problem.
  - In plugin 'pegasus' type 'com.linkedin.pegasus.gradle.tasks.GenerateDataTemplateTask' method 'generateLowercasePath()' should not be annotated with: @Optional, @Input.

    Reason: Input/Output annotations are ignored if they are placed on something else than a getter.

    Possible solutions:
      1. Remove the annotations.
      2. Rename the method.

    Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#ignored_annotations_on_method for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
1 actionable task: 1 executed

can anyone help me with this?

**Comment by ChrisCarini** [comment]
The [linkedin/rest.li](https://github.com/linkedin/rest.li) repository is being archived - see https://github.com/linkedin/rest.li/issues/1178 for details.

Ahead of it's archiving, we are closing all issues and PRs.
