### ISSUE TITLE
gradle publishRestliIdl not working

### ISSUE THREAD

**Issue by vshwnth2** [linkedin/rest.li#87]
Trying to run gradle publishRestliIdl but it is throwing an error

I followed the Quick start guide exactly, except am using pegasus version 11.0.0 instead of 11.0.17
gradle version 4.3.1, JVM 1.8.0_121

> Task :server:generateRestModel FAILED
[main] INFO com.linkedin.restli.tools.snapshot.gen.RestLiSnapshotExporter - Executing Rest.li annotation processor...
[main] INFO com.linkedin.restli.internal.server.model.RestLiAnnotationReader - Processed collection resource 'com.example.fortune.impl.FortunesResource'
[main] ERROR com.linkedin.restli.tools.snapshot.gen.RestLiSnapshotExporterCmdLineApp - Error writing Snapshot files
java.lang.NoClassDefFoundError: com/sun/javadoc/Doc
        at com.linkedin.restli.tools.snapshot.gen.RestLiSnapshotExporter.export(RestLiSnapshotExporter.java:136)
        at com.linkedin.restli.tools.snapshot.gen.RestLiSnapshotExporterCmdLineApp.main(RestLiSnapshotExporterCmdLineApp.java:106)
Caused by: java.lang.ClassNotFoundException: com.sun.javadoc.Doc
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 2 more
Error writing Snapshot files:
java.lang.NoClassDefFoundError: com/sun/javadoc/Doc

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':server:generateRestModel'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

**Comment by karthikbalasub** [comment]
Hi Mahesh,
    This issue is fixed in 11.0.17.
    If you want a temporary workaround on 11.0.0, you can add the following patch to your root gradle file:
allprojects {
  tasks.matching { it.name == 'generateRestModel'}.all {
    doFirst {
      it.codegenClasspath += files("${System.getProperty('java.home')}/../lib/tools.jar")
    }
  }
}

-Karthik

**Comment by vshwnth2** [comment]
The workaround worked! thanks!

If I try to use 11.0.17, I get this error:

> Task :api:generateDataTemplate FAILED
[main] INFO com.linkedin.pegasus.generator.PegasusDataTemplateGenerator - Generating 1 files
Exception in thread "main" java.io.IOException: /Users/maheshvishwanath/sante-restli/api/src/mainGeneratedDataTemplate/java: non-existent directory
        at com.sun.codemodel.writer.FileCodeWriter.<init>(FileCodeWriter.java:73)
        at com.linkedin.pegasus.generator.PegasusDataTemplateGenerator.run(PegasusDataTemplateGenerator.java:152)
        at com.linkedin.pegasus.generator.PegasusDataTemplateGenerator.main(PegasusDataTemplateGenerator.java:105)


FAILURE: Build failed with an exception.
